variables:
  - name: solution
    value: Seq.App.Teams.AdaptiveCard.sln
  - name: build_configuration
    value: Release
  - name: assemblyVersion
    value: 2.0.0
  - name: packageVersion
    value: 2.0.0
  - name: nugetDevVersion
    value: 2.0.1

trigger:
  - master
  - release
pr:
  branches:
    include:
    - '*'

stages:

- stage: ''
  displayName: ''
  jobs:
  - job: main_job
    pool:
      vmImage: 'ubuntu-latest'
    displayName: 'Seq.App.Teams.AdaptiveCard'

    steps:

#########
# BUILD #
#########

    - task: PowerShell@2
      inputs:
        filePath: '$(Build.SourcesDirectory)/ci/SetVersion.ps1'
        workingDirectory: '$(Build.SourcesDirectory)'
        arguments: -path $(Build.SourcesDirectory)/src/Seq.App.Teams.AdaptiveCard/Seq.App.Teams.AdaptiveCard.csproj -version $(assemblyVersion)
      displayName: Update assembly version

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '-property:ContinuousIntegrationBuild=true --configuration $(build_configuration)'
      displayName: Build Solution

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '$(Build.SourcesDirectory)/src/Seq.App.Teams.AdaptiveCard/Seq.App.Teams.AdaptiveCard.csproj'
        publishWebProjects: false
        zipAfterPublish: false
        arguments: -f netstandard2.0 -c Release
        nobuild: true
      displayName: Publish project

################
# CREATE NUGET #
################

    - powershell: echo "##vso[task.setvariable variable=packageVersion]$(nugetDevVersion)-rc.$(Build.BuildId)"
      displayName: Update nuget version
      condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'release'))

    - task: PowerShell@2
      inputs:
        filePath: '$(Build.SourcesDirectory)/ci/BuildNuspecs.ps1'
        workingDirectory: '$(Build.SourcesDirectory)'
        arguments: -path $(Build.SourcesDirectory)/ci/Seq.App.Teams.AdaptiveCard.nuspec -version $(packageVersion) -branch $(Build.SourceBranchName)
      displayName: Update nuspecs

    - task: CmdLine@2
      inputs:
        script: nuget pack $(Build.SourcesDirectory)/ci/Seq.App.Teams.AdaptiveCard.nuspec -OutputDirectory $(Build.SourcesDirectory)/.build/nuget
        workingDirectory: $(Build.SourcesDirectory)/ci
      displayName: Build nuget for artifacts
      condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'release'))

    - task: CmdLine@2
      inputs:
        script: nuget pack $(Build.SourcesDirectory)/ci/Seq.App.Teams.AdaptiveCard.nuspec -OutputDirectory $(Build.SourcesDirectory)/.build/nuget -Symbols -SymbolPackageFormat snupkg
        workingDirectory: $(Build.SourcesDirectory)/ci
      displayName: Build nuget for nuget.org
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'release'))

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.SourcesDirectory)/.build/nuget'
        artifactName: 'nuget'
      displayName: Publish nuget to artifacts

########
# TEST #
########

    - script: dotnet test $(Build.SourcesDirectory)/$(solution) -c $(build_configuration) -l trx
      displayName: 'Run Tests'
      condition: succeededOrFailed()

    - task: PublishTestResults@2
      inputs:
        testRunner: VsTest
        testResultsFiles: '**/*.trx'
        testRunTitle: 'Tests'
        failTaskOnMissingResultsFile: true
      displayName: 'Publish test results'
      condition: succeededOrFailed()

#################
# PUBLISH NUGET #
#################

    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.SourcesDirectory)/.build/nuget/Seq.App.Teams.AdaptiveCard.*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'projects/projects'
      displayName: Publish to Azure Artifacts feed
      condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'release'))

    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.SourcesDirectory)/.build/nuget/Seq.App.Teams.AdaptiveCard.*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'nuget.org'
      displayName: Publish to Nuget.org
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'release'))

